### ISSUE TITLE
New API in libassimp-dev 3.0 breaks cram_physics_utils

### ISSUE THREAD

**Issue by jannikb** [cram-code/cram_highlevel#40]
Ubuntu 14.04 comes with libassimp-dev 3.0 (Ubuntu 12.04 has 2.0) which has a new API. This causes cram_physics_utils to fail loading because it cannot find the includes.
I forked the repo and changed the includes to the new API and the package loads without errors again. I haven't made a pull request yet because I don't know how to use all functions so some might still be broken and it will probably break under 12.04.

**Comment by fairlight1337** [comment]
Did you have a look at the CMakeLists.txt and the file in the patch directory?

That problem persisted before and we introduced a workaround by automatically applying a patch when compiling the package.

**Comment by gaya-** [comment]
Similar issue: https://github.com/cram-code/cram_highlevel/pull/39

**Comment by jannikb** [comment]
@fairlight1337 That patch should fix the problem but it isn't applied anymore since the package was catkinized a2f6a8203b37023f22a57c4f1f26bd787ae1665e

**Comment by gaya-** [comment]
If the patch is needed only for Ubuntu 12.10 and not 12.04 and 14.04 then I don't think we need that patch. We could just fix the headers in the original source file and that's it. So for which versions of Ubuntu was this patch needed?

**Comment by fairlight1337** [comment]
12.10, I was working on that before switching to 14.04

**Comment by gaya-** [comment]
Merged https://github.com/cram-code/cram_highlevel/pull/39 in.
That should solve this issue, is that right @jannikb?

**Comment by jannikb** [comment]
@gaya- fixed it for indigo but under hydro with ubuntu 12.04 i get the following error:
```
External process exited with code 1.
Command was: "g++" "-m64" "-I/opt/ros/hydro/share/cffi/src/" "-o" "/home/jannikbu/.cache/common-lisp/sbcl-1.0.55.0.de..." "/home/jannikbu/.cache/common-lisp/sbcl-1.0.55.0.de..."
Output was:
/home/jannikbu/.cache/common-lisp/sbcl-1.0.55.0.debian-linux-x64/home/jannikbu/urdf_ws/src/cram_highlevel/cram_physics_utils/src/assimp-grovel.c:6:28: fatal error: assimp/cimport.h: No such file or directory
compilation terminated.
```

**Comment by gaya-** [comment]
I was so sure that the old headers were working in 12.04. Turns out I was wrong, sorry. Yeah, let's put the patch back into the CMakeLists. Give me a few minutes.

**Comment by gaya-** [comment]
https://github.com/cram-code/cram_highlevel/pull/43

@jannikb, could you please test this and see if it helps?

**Comment by gaya-** [comment]
So much for the "few minutes"...

**Comment by jannikb** [comment]
Works for me under hydro.

**Comment by gaya-** [comment]
Great, thanks!
